name: Fazer Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Executar comando de deploy
        run: |
          echo "Seu código de deploy vai aqui"
          echo "Exemplo: npm install e npm run build"